# Generated by Django 4.2.5 on 2023-12-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilingprofile',
            name='last4',
            field=models.CharField(max_length=50),
        ),
    ]
