# Generated by Django 4.2.5 on 2023-12-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_profiles', '0002_alter_bilingprofile_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilingprofile',
            name='exp_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bilingprofile',
            name='exp_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bilingprofile',
            name='livemode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bilingprofile',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
