# Generated by Django 4.2.5 on 2023-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_profiles', '0003_bilingprofile_exp_month_bilingprofile_exp_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilingprofile',
            name='cvc',
            field=models.IntegerField(default=0),
        ),
    ]
