# Generated by Django 4.1.1 on 2022-10-23 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.commo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biling_profiles', '0001_initial'),
        ('promo_code', '0001_initial'),
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[(orders.commo.OrderStatus['CREATED'], 'CREATED'), (orders.commo.OrderStatus['PAYED'], 'PAYED'), (orders.commo.OrderStatus['COMPLETED'], 'COMPLETED'), (orders.commo.OrderStatus['CANCELED'], 'CANCELED')], default=orders.commo.OrderStatus['CREATED'], max_length=50)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biling_profiles.bilingprofile')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('promo_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_code.promocode')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping_addresses.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
